version: "3.9"
services:
  web:
    image: web:v1
    container_name: web
    depends_on:
      - catalogue
  mongodb:
    image: mongodb:v1
    container_name: mongo
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb